[package]
name = "wave-motion-gun"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]
ggez = { git = "https://github.com/ggez/ggez.git", branch = "gamestate-rework"}
#ggez-goodies = { git = "https://github.com/ggez/ggez-goodies.git"}
rand = "0.3"
nalgebra = "0.10.*"
